# fly.toml file generated for fullstack11 on 2023-05-03T04:12:22+03:00

app = "fullstack11"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.13.0"

[[services]]
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "60s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000

  [[services.script_checks]]
    interval = 10000
    grace_period = "60s"
    command = "./app/health_check.sh"
    timeout = 2000
    restart_limit = 0