name: Hello World!

on:
  push:
    branches:
      - master
      
  workflow_dispatch:
      
jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: date
      - name: Directory content
        run: ls -l
      - name: Repository variable test
        run: echo "Repository variable is ${{ env.PRODUCTION_WEBSITE }}"
      
