name: Testing stuff

on:
  push:
    branches:
      - master
      
  workflow_dispatch:

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Repository variable test
        run: echo "Repository variable is ${{ env.PRODUCTION_WEBSITE }}"
